spring:
  datasource:
    url: jdbc:mysql://localhost/app
    username: root
    password: Juchimochi0330
    driverClassName: com.mysql.jdbc.Driver
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE